binutils rework

diff --git a/binutils/ar b/binutils/ar
--- a/binutils/ar
+++ b/binutils/ar
@@ -2,7 +2,7 @@
 #
 # Copyright 2006 by Brian Dominy <brian@oddchange.com>
 #
-# Changes by David Flamand <dflamand@gmail.com> (May 2016)
+# Changes by David Flamand <dflamand@gmail.com> (June 2016)
 #  - cleanup, more robust and verbose in case of error
 #
 # This file is part of GCC6809.
@@ -32,10 +32,18 @@ IFS=' '
 as_prefix=@AS_PREFIX@
 bindir=${as_prefix}/bin
 
-# Output a message to stderr and exit with a faillure code.
+showversion () {
+cat <<END
+ar (m6809) [GNU archiver frontend] 0.3 20160608
+This program is free software; you may redistribute it under the terms of
+the GNU General Public License.  This program has absolutely no warranty.
+END
+}
+
+# Output a message to stderr and exit with a failure code.
 error ()
 {
-	echo "ar (m6809): $1" 1>&2
+	echo "ar (m6809): $1" >&2
 	exit 1
 }
 
@@ -87,6 +95,14 @@ libcachetool ()
 options=${1#-}
 if [ -n "$options" ]; then
 	case $options in
+		-version)
+			showversion
+			exit 0
+			;;
+		help|-help)
+			cat $0 # TODO
+			exit 0
+			;;
 		C|-cache)
 			shift; libcachetool "$@"
 			;;
@@ -111,5 +127,5 @@ if [ -z "$options" ]; then
 	error "no options given"
 fi
 
-# Run the real archiver with translated options.
+# Invoke the real assembler with translated options.
 exec $bindir/aslib $options "$@"
diff --git a/binutils/as b/binutils/as
--- a/binutils/as
+++ b/binutils/as
@@ -1,6 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Copyright 2006 by Brian Dominy <brian@oddchange.com>
+#
+# Changes by David Flamand <dflamand@gmail.com> (June 2016)
+#  - more robust and verbose in case of error
 #
 # This file is part of GCC6809.
 #
@@ -19,37 +22,51 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 #
 
+# This script is a frontend to the as6809 assembler, to make it
+# look more like GNU as.  Not all as features are supported here.
+# It basically translates as style options into as6809 format.
+
+set -e
+IFS=' '
+
 as_prefix=@AS_PREFIX@
 bindir=${as_prefix}/bin
 
-show_version () {
+showversion () {
 cat <<END
-as6809 (GNU assembler frontend) 0.2 20061016
+as (m6809) [GNU assembler frontend] 0.3 20160608
 This program is free software; you may redistribute it under the terms of
 the GNU General Public License.  This program has absolutely no warranty.
 END
 }
 
-fatal_error () {
-	echo $* 1>&2
+# Output a message to stderr and exit with a failure code.
+error ()
+{
+	echo "as (m6809): $1" >&2
 	exit 1
 }
 
 # Assume nothing.
-
 input_file=
-output_file=
 list_file=
-options=
-list_file_enabled=n
+gen_list_file=
+output_file=
+verbose=
+version=
+
+# The -o option causes an object file to be created.
+# The -g option causes undefined symbols to be made global.
+options=-og
 
 # Parse the command-line options.  See the GNU 'as' man page for
 # an explanation of all these options.  Our goal is to translate
 # them into as6809 form.
-
-while [ "$1" != "" ]; do
+while [ $# -gt 0 ]; do
 	arg=$1; shift
 	case $arg in
+############################################################
+# these are custom assember options (no GNU as equivalent) #
 		-m6809)
 			true
 			;;
@@ -61,35 +78,39 @@ while [ "$1" != "" ]; do
 			# Generate SDCC debug symbols
 			options="${options}y"
 			;;
+############################################################
 		--globalize-symbols)
 			# Make all symbols global
 			options="${options}a"
 			;;
 		-m*)
-			fatal_error "invalid CPU option '$arg'"
+			error "invalid CPU option '$arg'"
 			;;
 		--)
-			fatal_error "standard input not supported"
+			error "standard input not supported"
 			;;
 		-a*)
 			options="${options}lc"
-			list_file_enabled=y
+			gen_list_file=X
 			;;
 		-I*)
-			#include_file=${arg#-I}
-			#echo "warning: include path '$include_file' ignored"
+#			#include_file=${arg#-I}
+#			#echo "warning: include path '$include_file' ignored"
 			;;
 		-MD)
-			fatal_error "assembler option '$arg' not supported"
+			error "assembler option '$arg' not supported"
 			;;
 		-o)
 			output_file=$1; shift
 			;;
-		-v|-version)
-			show_version
+		-v|-verbose|--verbose)
+			verbose=X
 			;;
-		--version)
-			show_version
+		-version|--version)
+			version=X
+			;;
+		-help|--help)
+			cat $0 # TODO
 			exit 0
 			;;
 		-D|-f|-K|--traditional-format|-w|-x|-Z|-W|--no-warn)
@@ -101,35 +122,62 @@ while [ "$1" != "" ]; do
 			list_file=${arg#=}
 			;;
 		-*)
-			echo "as (m6809): unrecognized option $arg"
-			exit 1
+			error "unrecognized option '$arg'"
 			;;
 		*)
-			input_file=$arg
-			asoutput_file=${input_file%\.[sS]}.rel
-			if [ "x$list_file_enabled" = "xy" ]; then
-				aslist_file=${input_file%\.[sS]}.lst
-				if [ "x$list_file" = "x" ]; then
-					list_file=$aslist_file
-				fi
+			if [ -n "$input_file" ]; then
+				error "more than one input file specified"
 			fi
+			if [ "${arg%.*}" = "$arg" ]; then
+				error "input file '$arg' without extension"
+			fi
+			input_file=$arg
 			;;
 	esac
 done
 
-# Complain if no input files given.  We don't support redirecting
-# from standard input.
-
-if [ "x$input_file" = "x" ]; then
-	fatal_error "no input file specified"
+# Setup various file name.
+asoutput_file=${input_file%\.*}.rel
+if [ -n "$gen_list_file" ]; then
+	aslist_file=${input_file%\.*}.lst
+	if [ -z "$list_file" ]; then
+		list_file=$aslist_file
+	fi
 fi
 
-# Invoke the real (as6809) assembler.
-# The -o option causes an object file to be created.
-# The -g option causes undefined symbols to be made global.
+# Output version information.
+if [ -n "$version" -o -n "$verbose" ]; then
+	showversion
+fi
+if [ -n "$version" ]; then
+	exit 0
+fi
 
-$bindir/as6809 -og$options $input_file
+# Output more information when --verbose option is set.
+if [ -n "$verbose" ]; then
+	echo "$bindir/as6809 $options $input_file"
+	echo "Output file: '$output_file'"
+	if [ -n "$gen_list_file" ]; then
+		echo "List file: '$list_file'"
+	fi
+fi
+
+# Exit if no input files given.
+# We don't support redirecting from standard input.
+if [ -z "$input_file" ]; then
+	if [ -n "$verbose" ]; then
+		exit 0
+	fi
+	error "no input file specified"
+fi
+
+set +e
+
+# Invoke the real assembler with translated options.
+$bindir/as6809 $options "$input_file"
 rc=$?
+
+set -e
 
 # OK, see if the assembler succeeded or not.
 # If it failed, the source is copied to /tmp/as6809_error.s
@@ -139,24 +187,28 @@ rc=$?
 #
 # Also, as6809 still creates a .o file even on an error;
 # that can confuse 'make'.  So delete the output file.
-
 if [ "$rc" != "0" ]; then
-	cp -p $input_file /tmp/as6809_error.s
-	rm -f $asoutput_file
+	# Make sure that the input file is valid before copying.
+	if [ -f "$input_file" ]; then
+		cp -p "$input_file" /tmp/as6809_error.s || true
+	fi
+	rm -f "$asoutput_file"
+	if [ -n "$gen_list_file" ]; then
+		rm -f "$aslist_file"
+	fi
 	exit $rc
 fi
 
 # as6809 creates the output file with the same name as the
-# input file, but with a .o extension.  The user may want
+# input file, but with a .rel extension.  The user may want
 # a different filename altogether, so honor that request here.
-
 if [ "$asoutput_file" != "$output_file" ]; then
-	mv $asoutput_file $output_file
+	mv "$asoutput_file" "$output_file"
 fi
 
-if [ "x$list_file_enabled" = "xy" ]; then
-	if [ "$aslist_file" != "$list_file" ]; then
-		mv $aslist_file $list_file
-	fi
+# Same as above but for the list file with a .lst extension.
+if [ -n "$gen_list_file" -a "$aslist_file" != "$list_file" ]; then
+	mv "$aslist_file" "$list_file"
 fi
 
+exit 0
diff --git a/binutils/ld b/binutils/ld
--- a/binutils/ld
+++ b/binutils/ld
@@ -2,7 +2,7 @@
 #
 # Copyright 2006, 2007 by Brian Dominy <brian@oddchange.com>
 #
-# Changes by David Flamand <dflamand@gmail.com> (May 2016)
+# Changes by David Flamand <dflamand@gmail.com> (June 2016)
 #  - added more options, more robust and verbose in case of error
 #
 # This file is part of GCC6809.
@@ -32,21 +32,19 @@ IFS=' '
 as_prefix=@AS_PREFIX@
 bindir=${as_prefix}/bin
 
-# Output a message to stdout or stderr and optionally exit with a code.
-msg ()
+showversion () {
+cat <<END
+ld (m6809) [GNU linker frontend] 0.3 20160608
+This program is free software; you may redistribute it under the terms of
+the GNU General Public License.  This program has absolutely no warranty.
+END
+}
+
+# Output an error message to stderr and exit with a failure code.
+error ()
 {
-	out=1
-	text="ld (m6809)"
-	if [ -n "$1" ]; then
-		text="$text: $1"
-	fi
-	if [ "0$2" -ne 0 ]; then
-		out=2
-	fi
-	echo "$text" >&$out
-	if [ $# -gt 1 ]; then
-		exit $2
-	fi
+	echo "ld (m6809): $1" >&2
+	exit 1
 }
 
 # Check if a given filename will survive a variable expansion.
@@ -57,7 +55,7 @@ checkfilename ()
 	A=$1; shift; B=$*
 	IFS=$OIFS
 	if [ -z "$A" -o "$A" != "$B" ]; then
-		msg "$MSG '$A'" 1
+		error "$MSG '$A'"
 	fi
 }
 
@@ -78,25 +76,42 @@ setformat ()
 			exe_suffix=$1
 			;;
 		*)
-			msg "unrecognized output format '$1'" 1
+			error "unrecognized output format '$1'"
 			;;
 	esac
 }
 
-# Set defaults.  Some are based on the target type, which is 
-# determined by the name by which the program was invoked.
-aslink_options=-nwxsar
+# Assume nothing.
+args=
+asmap_file=
+asoutput_file=
+crt0_file=
 exe_suffix=
+gen_map_file=
+input_files=
+libpaths=
+libs=
+map_file=
+noargs=
 options=
 target=
-case $0 in
-	*m6809-coco-*)
+verbose=
+version=
+
+# Set defaults.
+aslink_options=-nwxsar
+output_file=a.out
+
+# Try to guest the target type, which is determined
+# by the name by which the program was invoked.
+case ${0##*/} in
+	coco-*|*-coco-*|*-coco)
 		options="-b .text=0x2000 -b .data=0x7000 -b .bss=0x7C00 -b .ctors=0x7F00 -b .dtors=0x7F80 -b .vector=0x7FF0"
 		target=coco
 		setformat bin
 		LD_NOARGS=X
 		;;
-	*m6809-sim-*)
+	sim-*|*-sim-*|*-sim)
 		options="-b .text=0x10 -b .vector=0xFFF0"
 		target=sim
 		setformat s19
@@ -111,21 +126,36 @@ case $0 in
 esac
 
 # Parse and translate command-line options.
-output_file=a.out
-args=
-asmap_file=
-asout_file=
-gen_map_file=
-input_files=
-libpaths=
-libs=
-map_file=
-noargs=
-verbose=
-version=
 while [ $# -gt 0 ]; do
 	arg=$1; shift
 	case $arg in
+##########################################################
+# these are custom linker options (no GNU ld equivalent) #
+		-gn)
+			# Generate NoICE debug file
+			aslink_options="${aslink_options}j"
+			;;
+		-gs)
+			# Generate SDCC debug file
+			aslink_options="${aslink_options}y"
+			;;
+		--map)
+			# Generate map file
+			gen_map_file=X
+			;;
+		--args)
+			# Prototype of main():
+			#  if supplied main() prototype is
+			#    int main(int argc, char **argc)
+			#  if not supplied main() prototype is
+			#    int main(void)
+			args=X
+			;;
+		--noargs)
+			# The inverse of the above
+			noargs=X
+			;;
+##########################################################
 		-o|--output)
 			output_file=$1; shift
 			;;
@@ -189,18 +219,18 @@ while [ $# -gt 0 ]; do
 		-Ttext)
 			options="$options -b .text=$1"; shift
 			;;
-		--verbose)
-			verbose=X
-			;;
 		-g)
 			# Ignored by GNU ld; we should do the same
 			true
 			;;
-		-v|--version)
+		-v|-verbose|--verbose)
+			verbose=X
+			;;
+		-version|--version)
 			version=X
 			;;
-		--help)
-			cat $0 # Better than nothing
+		-help|--help)
+			cat $0 # TODO
 			exit 0
 			;;
 		-T)
@@ -214,48 +244,29 @@ while [ $# -gt 0 ]; do
 			map_file=${arg#*=}
 			gen_map_file=X
 			;;
-##########################################################
-# these are custom linker options (no GNU ld equivalent) #
-		-gn)
-			# Generate NoICE debug file
-			aslink_options="${aslink_options}j"
-			;;
-		-gs)
-			# Generate SDCC debug file
-			aslink_options="${aslink_options}y"
-			;;
-		--map)
-			# Generate map file
-			gen_map_file=X
-			;;
-		--args)
-			# Prototype of main():
-			#  if supplied main() prototype is
-			#    int main(int argc, char **argc)
-			#  if not supplied main() prototype is
-			#    int main(void)
-			args=X
-			;;
-		--noargs)
-			# The inverse of the above
-			noargs=X
-			;;
-##########################################################
 		-*)
-			msg "unrecognized option '$arg'" 1
+			error "unrecognized option '$arg'"
+			;;
+		*/crt0.o|crt0.o)
+			checkfilename "invalid input file name" "$arg" $arg
+			if [ -n "$crt0_file" ]; then
+				error "more than one crt0.o given"
+			fi
+			crt0_file=$arg
 			;;
 		*)
 			checkfilename "invalid input file name" "$arg" $arg
 			if [ "${arg%.*}" = "$arg" ]; then
-				msg "input file '$arg' without extension" 1
+				error "input file '$arg' without extension"
 			fi
 			input_files="$input_files $arg"
 			;;
 	esac
 done
 
-asout_file=${output_file%\.*}.$exe_suffix
-asmap_file=${asout_file%\.*}.map
+# Setup various file name.
+asoutput_file=${output_file%\.*}.$exe_suffix
+asmap_file=${asoutput_file%\.*}.map
 if [ -z "$map_file" ]; then
 	map_file=${output_file%\.*}.map
 fi
@@ -276,12 +287,15 @@ fi
 
 # Output version information.
 if [ -n "$version" -o -n "$verbose" ]; then
-	msg ""
+	showversion
+fi
+if [ -n "$version" ]; then
+	exit 0
 fi
 
 # Output more information when --verbose option is set.
 if [ -n "$verbose" ]; then
-	echo "$bindir/aslink $aslink_options $options $asout_file $input_files $libpaths $libs"
+	echo "$bindir/aslink $aslink_options $options $asoutput_file $crt0_file $input_files $libpaths $libs"
 	echo "Target: '$target'"
 	echo "Output format: '$exe_suffix'"
 	echo "Output file: '$output_file'"
@@ -290,38 +304,43 @@ if [ -n "$verbose" ]; then
 	fi
 fi
 
-# Exit if no input file.
+# Exit if no input files given.
 if [ -z "$input_files" ]; then
-	if [ -n "$version" -o -n "$verbose" ]; then
+	if [ -n "$verbose" ]; then
 		exit 0
 	fi
-	msg "no input files" 1
+	error "no input files"
 fi
 
-if [ -n "$gen_map_file" ]; then
+if [ -n "$gen_map_file" -a -e "$asmap_file" ]; then
 	rm -f "$asmap_file"
 fi
 
 set +e
 
-# Run the real linker with translated options.
-$bindir/aslink $aslink_options $options "$asout_file" $input_files $libpaths $libs
+# Invoke the real linker with translated options.
+$bindir/aslink $aslink_options $options "$asoutput_file" $crt0_file $input_files $libpaths $libs
 rc=$?
 
 set -e
 
+# Do some cleanup in case of error.
 if [ "$rc" != "0" ]; then
-	rm -f "$asout_file"
-	if [ -n "$gen_map_file" ]; then
+	rm -f "$asoutput_file"
+	if [ -n "$gen_map_file" -a -e "$asmap_file" ]; then
 		rm -f "$asmap_file"
 	fi
 	exit $rc
 fi
 
-if [ "$asout_file" != "$output_file" ]; then
-	mv "$asout_file" "$output_file"
+# aslink creates the output file with the same name as the
+# input file, but with a .s19|.bin|.ihx extension.  The user may want
+# a different filename altogether, so honor that request here.
+if [ "$asoutput_file" != "$output_file" ]; then
+	mv "$asoutput_file" "$output_file"
 fi
 
+# Same as above but for the map file with a .map extension.
 if [ -n "$gen_map_file" -a "$asmap_file" != "$map_file" ]; then
 	mv "$asmap_file" "$map_file"
 fi
